config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :news

  root 'news#index'

  # get '/search', to 'nyt#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/news_controller.rb
require "httparty"

class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
    
  # GET /news
  # GET /news.json
  # NYT-api to be moved to another controller
  def index
    key = "7a3872ec641840f6a31b6b4da77aad1d"
    search ="bees"
    startYear = '20160101'
    endYear = '20170101'
    url = 'http://api.nytimes.com/svc/search/v2/articlesearch.json?api_key='+key+'&q='+search+'&begin_date='+startYear+'&end_date='+endYear
    response = HTTParty.get(url)

    # puts response

    @article = response["response"]["docs"]

    @news = News.new

  end

  # GET /news/1
  # GET /news/1.json
  def shows
    @news = News.find(params[:id])
  end

  # GET /news/new
  def new
    @news = News.all
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)
    # puts news_params

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_index_url, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_index_url, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to "/news/new", notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :snippet, :url)
    end
end

app/controllers/nyt_controller.rb
class NytController < ApplicationController
	
	def search
		# moved to news#index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/nyt_api_helper.rb
module NytApiHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NYT Search Page</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/">Home</a></li>
          <li><a href="/news/new">Saved Articles</a></li>
        </ul>
      </div>
    </nav>
    <div class="conatiner">
      <div class="jumbotron text-center">
        <h1 class="mainTitle">New York Times News Search</h1>
        <hr/>
        <p>Search and save your favorite NYT article in one place!</p>
        <div class="searchBox">
          <input type="text" class="form-control mainSearch" placeholder="Start searching!">
            <button class="btn btn-info" type="button"><span class="glyphicon glyphicon-search"></span></button>
        </div>
      </div>
      <div class="container">
        <%= yield %>  
      </div>
    </div>
  </body>
</html>

<!-- Deleted forms for search button -->

app/views/news/_form.html.erb
<!-- Usable for future need to input to database through form -->

<%= form_for(news) do |f| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :snippet %>
    <%= f.text_field :snippet, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<div>
  <% @article.each do |art| %>
  <span class="thumbnail">
    <%= image_tag "http://www.nytimes.com/"+art["multimedia"][0]["url"] %>
    <hr/>
    <div class="caption">
      <h3 id="headline"><%= art["headline"]["main"] %></h3>
      <p><%= art["snippet"] %>... 
        <%= link_to "Read more..", art["web_url"], target: "_blank" %>
      </p>
      <%= button_to 'Save', 
        {:controller => "news", 
        :action => "create", 
        :news => {:title => art["headline"]["main"], 
        :snippet => art["snippet"],
        :url => art["web_url"]}}, 
        :method=>:post  
      %>
    </div> 
  </span>
  <% end %>
</div>

app/views/news/new.html.erb
<p id="notice"><%= notice %></p>
<h1 class="saveTitle">Saved News Articles</h1>
<ul class="list-group">
	<% @news.each do |news| %>
		<li class="list-group-item">
			<h3><%= news.title %></h3>
			<p><%= news.snippet %>... <%= link_to 'More', "#{news.url}", target: "_blank" %></p>
			<%= link_to 'Delete', news, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
		</li>
	<% end %>
</ul>